### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by adrix71** [SIB-FRANCE/Polyfony2#122]
When i try this framework received this error:

`Warning: symlink(): Could not fetch file information(error 3) in C:\wamp64\www\polyfony\Private\Vendor\Polyfony\Filesystem.php on line 122`

From home page the link Demo and Tools not work.

**Comment by AnnoyingTechnology** [comment]
I think it has never ran on a Microsoft system.
Being a web framework, It is assumed that the environment is a Unix system.
It works perfectly on Linux and MacOS (I just did a checkout of the repo just now).

**Comment by AnnoyingTechnology** [comment]
I also see from the error that your are using Apache. 
The framework is mostly ran behind fast webservers : nginx and Lighttpd. 
Apache *should* be supported.

**Comment by adrix71** [comment]
In practice, the database does not support mysql, the framework does not support windows and apache.

OK, perfect. Step further

**Comment by AnnoyingTechnology** [comment]
Yes sorry, I will update the readme accordingly. 

I think it ran on apache about 5 years ago. 
There was an very simple .htaccess file. Basically, it said "rewrite all requests that don't match a physical file to index.php".

It runs very smoothly on UNIX + lighttpd + PHP-[CGI/FPM/FCGI] (greater than 5.3 and lower that 7.2) 7.1 is supported.

**Comment by adrix71** [comment]
Tried on linux it works and I like it.

Tested on Android (Galaxy S8) and it works.

I know I will make a port to adapt it to any operating system.

Thanks for the answers.

**Comment by AnnoyingTechnology** [comment]
Good to know. If you have time, during or after your project feel free to give us some feedback about your experience with this framework.

**Comment by adrix71** [comment]
I will do it. Count on it.

Meanwhile, I wish happy new year to you and everyone.
