### ISSUE TITLE
Query->whereIsNot()

### ISSUE THREAD

**Issue by AnnoyingTechnology** [SIB-FRANCE/Polyfony2#27]
SQL `!=`

**Comment by Jijac** [comment]
Most implementations support the ANSI standard operator <> as well as the != operator that is familiar to users of most popular programming languages.

MySQL 5.1: supports both != and <>
PostgreSQL 8.3: supports both != and <>
SQLite: supports both != and <>
Oracle 10g: supports both != and <>
Microsoft SQL Server 2000/2005/2008: supports both != and <>
IBM Informix Dynamic Server 10: supports both != and <>
InterBase/Firebird: supports both != and <>
Apache Derby 10.6: supports both != and <>
Sybase Adaptive Server Enterprise 11.0: supports both != and <>
These support only the ANSI standard operator:

IBM DB2 UDB 9.5: supports only <>
Microsoft Access 2010: supports only <>
edited Jul 25 '13 at 1:52

**Comment by AnnoyingTechnology** [comment]
merci @Jijac
