### ISSUE TITLE
Security :  redirect to Config[router] exit_route when logout

### ISSUE THREAD

**Issue by Jijac** [SIB-FRANCE/Polyfony2#28]
// internal method to refuse access
	private static function refuse($message='Forbidden', $code='403', $logout=false, $redirect=true) {
		// remove any existing session cookie
		!$logout ?: Store\Cookie::remove(Config::get('security','cookie'));

		if($logout) {
			// we will redirect to the logout page
			!$redirect ?: Response::setRedirect(Config::get('router','exit_route'), 3);
		} else {
			// we will redirect to the login page
			!$redirect ?: Response::setRedirect(Config::get('router','login_route'), 3);
		}
		// trhow a polyfony exception that by itself will stop the execution with maybe a nice exception handler
		Throw new Exception($message,$code);
	}

**Comment by AnnoyingTechnology** [comment]
fixed in https://github.com/SIB-FRANCE/Polyfony2/commit/81ef3504f45a34ff2af80476a276d2efcb043c9e
