### ISSUE TITLE
Database set null issues

### ISSUE THREAD

**Issue by AnnoyingTechnology** [SIB-FRANCE/Polyfony2#36]
Columns using _date magic will fail to get the proper SQL NULL, they get an empty value '' instead

```php
// close all sessions
Pf\Database::query()
	->update('Accounts')
	->set(array(
		'session_expiration_date'	=>null,
		'session_key'				=>null,
		'last_login_origin'			=>null,
		'last_login_agent'			=>null,
		'last_login_date'			=>null,
		'last_failure_origin'		=>null,
		'last_failure_agent'		=>null,
		'last_failure_date'			=>null,
	))
	->execute();
```
last_failure_date, last_login_date, session_expiration_date have empty values, all other have NULL.

**Comment by Jijac** [comment]
peut-être un truc du genre

	// convert the value depending on the column name
	public static function convert($column,$value) {
		if($value == null){
			$value = 'NULL';
		}

non testé

**Comment by AnnoyingTechnology** [comment]
```php
=== // même !
```

**Comment by AnnoyingTechnology** [comment]
bref, c'est super simple, il faut juste ne pas appliquer le convertisseur si on a un vrai 
```php
null 
```
je m'en occupe

**Comment by AnnoyingTechnology** [comment]
d'ailleurs pour être un peu plus rigoureux le whereNull devrait tester pour NULL et chaine de caractère vide, pas pour 0. En revanche whereFalse devrait prendre tout ce que php évalue à false, donc 

```php
$this_is_fase = bool '';
$this_is_fase = bool 0;
$this_is_fase = bool false;
```

**Comment by AnnoyingTechnology** [comment]
ou alors whereNull est parfaitement strict, et on ajoute whereEmpty , qui prend "" et null. C'est mieux je pense, d'être plus strict.

**Comment by AnnoyingTechnology** [comment]
doc intéressante au passage https://sqlite.org/nulls.html

**Comment by WarenN** [comment]
je suis d'accord



W⍺rεηN
